// <auto-generated />
using System;
using CliniApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CliniApi.Migrations
{
    [DbContext(typeof(ClinicDbContext))]
    [Migration("20260524092440_FixSeedData")]
    partial class FixSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CliniApi.Domain.Entities.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime>("AppointmentTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("AppointmentId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            AppointmentId = 1,
                            AppointmentTime = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 5, 22, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            Note = "First visit",
                            PatientId = 1,
                            Reason = "Regular health check",
                            Status = "Scheduled"
                        },
                        new
                        {
                            AppointmentId = 2,
                            AppointmentTime = new DateTime(2026, 6, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 5, 22, 9, 10, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            Note = "Need ECG",
                            PatientId = 2,
                            Reason = "Chest pain",
                            Status = "Scheduled"
                        },
                        new
                        {
                            AppointmentId = 3,
                            AppointmentTime = new DateTime(2026, 6, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 5, 22, 9, 20, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            Note = "Completed successfully",
                            PatientId = 3,
                            Reason = "Fever",
                            Status = "Completed"
                        },
                        new
                        {
                            AppointmentId = 4,
                            AppointmentTime = new DateTime(2026, 6, 2, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 5, 22, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 3,
                            Note = "Patient cancelled",
                            PatientId = 4,
                            Reason = "Child cough",
                            Status = "Cancelled"
                        },
                        new
                        {
                            AppointmentId = 5,
                            AppointmentTime = new DateTime(2026, 6, 2, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 5, 22, 9, 40, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 3,
                            Note = "Bring previous record",
                            PatientId = 5,
                            Reason = "Pediatric consultation",
                            Status = "Scheduled"
                        },
                        new
                        {
                            AppointmentId = 6,
                            AppointmentTime = new DateTime(2026, 6, 3, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 5, 22, 9, 50, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 4,
                            Note = "Fasting required",
                            PatientId = 1,
                            Reason = "Abdominal ultrasound",
                            Status = "Scheduled"
                        },
                        new
                        {
                            AppointmentId = 7,
                            AppointmentTime = new DateTime(2026, 6, 3, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 5, 22, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 5,
                            Note = "Stable condition",
                            PatientId = 2,
                            Reason = "Follow-up check",
                            Status = "Completed"
                        },
                        new
                        {
                            AppointmentId = 8,
                            AppointmentTime = new DateTime(2026, 6, 4, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 5, 22, 10, 10, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            Note = "Monitor blood pressure",
                            PatientId = 6,
                            Reason = "Heart check",
                            Status = "Scheduled"
                        });
                });

            modelBuilder.Entity("CliniApi.Domain.Entities.AppointmentService", b =>
                {
                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AppointmentId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("AppointmentServices");

                    b.HasData(
                        new
                        {
                            AppointmentId = 1,
                            ServiceId = 1,
                            Quantity = 1,
                            UnitPrice = 200000m
                        },
                        new
                        {
                            AppointmentId = 1,
                            ServiceId = 2,
                            Quantity = 1,
                            UnitPrice = 150000m
                        },
                        new
                        {
                            AppointmentId = 2,
                            ServiceId = 4,
                            Quantity = 1,
                            UnitPrice = 250000m
                        },
                        new
                        {
                            AppointmentId = 3,
                            ServiceId = 1,
                            Quantity = 1,
                            UnitPrice = 200000m
                        },
                        new
                        {
                            AppointmentId = 4,
                            ServiceId = 6,
                            Quantity = 1,
                            UnitPrice = 180000m
                        },
                        new
                        {
                            AppointmentId = 5,
                            ServiceId = 6,
                            Quantity = 1,
                            UnitPrice = 180000m
                        },
                        new
                        {
                            AppointmentId = 6,
                            ServiceId = 3,
                            Quantity = 1,
                            UnitPrice = 300000m
                        },
                        new
                        {
                            AppointmentId = 7,
                            ServiceId = 1,
                            Quantity = 1,
                            UnitPrice = 200000m
                        },
                        new
                        {
                            AppointmentId = 8,
                            ServiceId = 4,
                            Quantity = 1,
                            UnitPrice = 250000m
                        });
                });

            modelBuilder.Entity("CliniApi.Domain.Entities.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorId"));

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("int");

                    b.HasKey("DoctorId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            DoctorId = 1,
                            Email = "an.nguyen@clinic.com",
                            FullName = "Dr. Nguyen Van An",
                            IsActive = true,
                            Phone = "0901000001",
                            SpecialtyId = 1
                        },
                        new
                        {
                            DoctorId = 2,
                            Email = "binh.tran@clinic.com",
                            FullName = "Dr. Tran Thi Binh",
                            IsActive = true,
                            Phone = "0901000002",
                            SpecialtyId = 2
                        },
                        new
                        {
                            DoctorId = 3,
                            Email = "chau.le@clinic.com",
                            FullName = "Dr. Le Minh Chau",
                            IsActive = true,
                            Phone = "0901000003",
                            SpecialtyId = 3
                        },
                        new
                        {
                            DoctorId = 4,
                            Email = "dung.pham@clinic.com",
                            FullName = "Dr. Pham Quoc Dung",
                            IsActive = true,
                            Phone = "0901000004",
                            SpecialtyId = 4
                        },
                        new
                        {
                            DoctorId = 5,
                            Email = "ha.hoang@clinic.com",
                            FullName = "Dr. Hoang Thu Ha",
                            IsActive = true,
                            Phone = "0901000005",
                            SpecialtyId = 1
                        },
                        new
                        {
                            DoctorId = 6,
                            Email = "khoa.do@clinic.com",
                            FullName = "Dr. Do Manh Khoa",
                            IsActive = false,
                            Phone = "0901000006",
                            SpecialtyId = 2
                        });
                });

            modelBuilder.Entity("CliniApi.Domain.Entities.MedicalService", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ServiceId");

                    b.ToTable("MedicalServices");

                    b.HasData(
                        new
                        {
                            ServiceId = 1,
                            IsActive = true,
                            Name = "General Check-up",
                            Price = 200000m
                        },
                        new
                        {
                            ServiceId = 2,
                            IsActive = true,
                            Name = "Blood Test",
                            Price = 150000m
                        },
                        new
                        {
                            ServiceId = 3,
                            IsActive = true,
                            Name = "Ultrasound",
                            Price = 300000m
                        },
                        new
                        {
                            ServiceId = 4,
                            IsActive = true,
                            Name = "Electrocardiogram",
                            Price = 250000m
                        },
                        new
                        {
                            ServiceId = 5,
                            IsActive = true,
                            Name = "X-ray",
                            Price = 350000m
                        },
                        new
                        {
                            ServiceId = 6,
                            IsActive = true,
                            Name = "Pediatric Consultation",
                            Price = 180000m
                        });
                });

            modelBuilder.Entity("CliniApi.Domain.Entities.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("PatientId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            Address = "Ha Noi",
                            DateOfBirth = new DateTime(1998, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Nguyen Minh Duc",
                            Gender = "Male",
                            Phone = "0912000001"
                        },
                        new
                        {
                            PatientId = 2,
                            Address = "Hai Phong",
                            DateOfBirth = new DateTime(2000, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Tran Thi Lan",
                            Gender = "Female",
                            Phone = "0912000002"
                        },
                        new
                        {
                            PatientId = 3,
                            Address = "Da Nang",
                            DateOfBirth = new DateTime(1995, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Le Hoang Nam",
                            Gender = "Male",
                            Phone = "0912000003"
                        },
                        new
                        {
                            PatientId = 4,
                            Address = "Ho Chi Minh City",
                            DateOfBirth = new DateTime(2002, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Pham Ngoc Mai",
                            Gender = "Female",
                            Phone = "0912000004"
                        },
                        new
                        {
                            PatientId = 5,
                            Address = "Can Tho",
                            DateOfBirth = new DateTime(2015, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Hoang Gia Bao",
                            Gender = "Male",
                            Phone = "0912000005"
                        },
                        new
                        {
                            PatientId = 6,
                            Address = "Bac Ninh",
                            DateOfBirth = new DateTime(1988, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Do Thanh Tam",
                            Gender = "Female",
                            Phone = "0912000006"
                        });
                });

            modelBuilder.Entity("CliniApi.Domain.Entities.Specialty", b =>
                {
                    b.Property<int>("SpecialtyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpecialtyId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("SpecialtyId");

                    b.ToTable("Specialties");

                    b.HasData(
                        new
                        {
                            SpecialtyId = 1,
                            Description = "General health examination",
                            Name = "General Medicine"
                        },
                        new
                        {
                            SpecialtyId = 2,
                            Description = "Heart and blood vessel care",
                            Name = "Cardiology"
                        },
                        new
                        {
                            SpecialtyId = 3,
                            Description = "Medical care for children",
                            Name = "Pediatrics"
                        },
                        new
                        {
                            SpecialtyId = 4,
                            Description = "Imaging and diagnostic services",
                            Name = "Radiology"
                        });
                });

            modelBuilder.Entity("CliniApi.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("CliniApi.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CliniApi.Domain.Entities.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("CliniApi.Domain.Entities.AppointmentService", b =>
                {
                    b.HasOne("CliniApi.Domain.Entities.Appointment", "Appointment")
                        .WithMany("AppointmentServices")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CliniApi.Domain.Entities.MedicalService", "MedicalService")
                        .WithMany("AppointmentServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("MedicalService");
                });

            modelBuilder.Entity("CliniApi.Domain.Entities.Doctor", b =>
                {
                    b.HasOne("CliniApi.Domain.Entities.Specialty", "Specialty")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("CliniApi.Domain.Entities.Appointment", b =>
                {
                    b.Navigation("AppointmentServices");
                });

            modelBuilder.Entity("CliniApi.Domain.Entities.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("CliniApi.Domain.Entities.MedicalService", b =>
                {
                    b.Navigation("AppointmentServices");
                });

            modelBuilder.Entity("CliniApi.Domain.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("CliniApi.Domain.Entities.Specialty", b =>
                {
                    b.Navigation("Doctors");
                });
#pragma warning restore 612, 618
        }
    }
}
